require 'hoe'
## require './lib/rubidity/version.rb'

Hoe.spec 'rubidity' do

  self.version =   '0.0.1'  ##Pixelart::Module::Ordgen::VERSION


  self.summary = 'Rubidity - Ruby for Layer 1 (L1) Contracts with "Off-Chain" Indexer'
  self.description = summary

  self.urls    = { home: 'https://github.com/s6ruby/rubidity' }

  self.author  = 'Gerald Bauer'
  self.email   = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['activesupport'],
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.3'
  }
end
