require 'hoe'
require './lib/scribelite/version.rb'


Hoe.spec 'scribelite' do
  self.version =  Scribelite::VERSION

  self.summary = "scribelite gem - inscription / inscribe (ethscription calldata) database for ethereum & co; let's you query via sql and more"
  self.description = summary

  self.urls    = { home: 'https://github.com/s6ruby/rubidity' }

  self.author  = 'Gerald Bauer'
  self.email   = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['ethscribe'], 
    ['calldata'],    ## todo - check if included via ethscribe in the future?  
    ['activerecord'],
    ['activerecord-utils'],
    ['logutils'],
    ['logutils-activerecord'],
    ['props'],
    ['props-activerecord'],
    ['sqlite3'],
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.3'
  }
end
