require 'hoe'
require './lib/rubysol/contracts/version.rb'

Hoe.spec 'rubysol-contracts' do

  self.version =  Rubysol::Module::Contracts::VERSION

  self.summary = 'rubysol-contracts - standard contracts (incl. erc20, erc721, etc) for ruby for layer 1 (l1) with "off-chain" indexer'
  self.description = summary

  self.urls    = { home: 'https://github.com/s6ruby/rubidity' }

  self.author  = 'Gerald Bauer'
  self.email   = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['rubysol', '>= 0.1.0'],
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.3'
  }
end
